export const DUMMY_FIELDS = [
  {
    displayOrder: 1,
    fieldName: 'header_1',
    fieldType: 'HEADER',
    isRequired: false,
    label: 'Company Information',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '1',
    triggersConditions: false,
    headerConfig: {
      style: 'H1',
      bold: true,
      italic: null,
      color: '#1A1A2E',
      alignment: 'left',
      icon: null,
      cssClass: null,
      linkSegments: null,
    },
  },
  {
    displayOrder: 2,
    fieldName: 'header_2',
    fieldType: 'HEADER',
    isRequired: false,
    label: 'Enter company identification data',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '2',
    triggersConditions: false,
    headerConfig: {
      style: 'SUBTITLE',
      bold: false,
      italic: null,
      color: '#868E96',
      alignment: 'left',
      icon: null,
      cssClass: null,
      linkSegments: null,
    },
  },
  {
    displayOrder: 3,
    fieldName: 'taxCode',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'Tax Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    triggersConditions: false,
    validationRule: {
      regex: '^[A-Za-z0-9]+$',
      minLength: 16,
    },
    // value: '123142545345345435345',
  },
  {
    displayOrder: 4,
    fieldName: 'radio',
    fieldType: 'RADIO',
    fieldWidth: '2',
    isRequired: true,
    label: 'Choose One',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    triggersConditions: false,
    fieldOptions: ['123', '456', '789'],
    // value: '123',
  },
  {
    displayOrder: 5,
    fieldName: 'multi',
    fieldType: 'MULTI_CHECKBOX',
    fieldWidth: '2',
    isRequired: true,
    label: 'Select Multiple',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    triggersConditions: false,
    fieldOptions: ['123', '456', '789'],
    // value: '456',
  },
  {
    displayOrder: 6,
    fieldName: 'group1',
    fieldType: 'GROUP',
    fieldWidth: '2',
    isRequired: true,
    label: 'Tax Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    fields: [
      {
        displayOrder: 7,
        fieldName: 'header_1',
        fieldType: 'HEADER',
        isRequired: false,
        label: 'Company Information',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '1',
        triggersConditions: false,
        headerConfig: {
          style: 'H1',
          bold: true,
          italic: null,
          color: '#1A1A2E',
          alignment: 'left',
          icon: null,
          cssClass: null,
          linkSegments: null,
        },
      },
      {
        displayOrder: 8,
        fieldName: 'radio1',
        fieldType: 'RADIO',
        fieldWidth: '2',
        isRequired: true,
        label: 'Choose One',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '123',
      },
      {
        displayOrder: 9,
        fieldName: 'multi2',
        fieldType: 'MULTI_CHECKBOX',
        fieldWidth: '2',
        isRequired: true,
        label: 'Select Multiple',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '456',
      },
      {
        displayOrder: 10,
        fieldName: 'multi3',
        fieldType: 'MULTI_CHECKBOX',
        fieldWidth: '2',
        isRequired: true,
        label: 'Select Multiple',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '789',
      },
      {
        displayOrder: 11,
        fieldName: 'group3',
        fieldType: 'GROUP',
        fieldWidth: '2',
        isRequired: true,
        isRepeatable: true,
        label: 'Tax Code',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        fields: [
          {
            displayOrder: 12,
            fieldName: 'taxCode_2',
            fieldType: 'TEXT',
            fieldWidth: '2',
            isRequired: true,
            label: 'Tax Code',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '3',
            triggersConditions: false,
            validationRule: {
              regex: '^[A-Za-z0-9]+$',
              minLength: 16,
            },
            // value: '123142545345345435345',
          },
          {
            displayOrder: 13,
            fieldName: 'taxCode_3',
            fieldType: 'TEXT',
            fieldWidth: '2',
            isRequired: true,
            label: 'Tax Code',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '3',
            triggersConditions: false,
            validationRule: {
              regex: '^[A-Za-z0-9]+$',
              minLength: 16,
            },
            // value: '123142545345345435345',
          },
          {
            displayOrder: 14,
            fieldName: 'header_1',
            fieldType: 'HEADER',
            isRequired: false,
            label: 'Company Information',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '1',
            triggersConditions: false,
            headerConfig: {
              style: 'H1',
              bold: true,
              italic: null,
              color: '#1A1A2E',
              alignment: 'left',
              icon: null,
              cssClass: null,
              linkSegments: null,
            },
          },
          {
            displayOrder: 15,
            fieldName: 'radio_3',
            fieldType: 'RADIO',
            fieldWidth: '2',
            isRequired: true,
            label: 'Choose One',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '3',
            triggersConditions: false,
            fieldOptions: ['123', '456', '789'],
            // value: '123',
          },
          {
            displayOrder: 16,
            fieldName: 'multi_4',
            fieldType: 'MULTI_CHECKBOX',
            fieldWidth: '2',
            isRequired: true,
            label: 'Select Multiple',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '3',
            triggersConditions: false,
            fieldOptions: ['123', '456', '789'],
            // value: '456',
          },
          {
            displayOrder: 17,
            fieldName: 'multi_5',
            fieldType: 'MULTI_CHECKBOX',
            fieldWidth: '2',
            isRequired: true,
            label: 'Select Multiple',
            pageOrder: 1,
            pageTitle: 'Company',
            rowGroup: '3',
            triggersConditions: false,
            fieldOptions: ['123', '456', '789'],
            // value: '789',
          },
        ],
        triggersConditions: false,
      },
    ],
    triggersConditions: false,
  },
  {
    displayOrder: 18,
    fieldName: 'group2',
    fieldType: 'GROUP',
    fieldWidth: '2',
    isRequired: true,
    isRepeatable: true,
    label: 'Tax Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    fields: [
      {
        displayOrder: 19,
        fieldName: 'taxCode1',
        fieldType: 'TEXT',
        fieldWidth: '2',
        isRequired: true,
        label: 'Tax Code',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        validationRule: {
          regex: '^[A-Za-z0-9]+$',
          minLength: 16,
        },
        // value: '123142545345345435345',
      },
      {
        displayOrder: 20,
        fieldName: 'taxCode2',
        fieldType: 'TEXT',
        fieldWidth: '2',
        isRequired: true,
        label: 'Tax Code',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        validationRule: {
          regex: '^[A-Za-z0-9]+$',
          minLength: 16,
        },
        // value: '123142545345345435345',
      },
      {
        displayOrder: 21,
        fieldName: 'header_1',
        fieldType: 'HEADER',
        isRequired: false,
        label: 'Company Information',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '1',
        triggersConditions: false,
        headerConfig: {
          style: 'H1',
          bold: true,
          italic: null,
          color: '#1A1A2E',
          alignment: 'left',
          icon: null,
          cssClass: null,
          linkSegments: null,
        },
      },
      {
        displayOrder: 40,
        fieldName: 'country1',
        fieldType: 'SELECT',
        fieldWidth: '3',
        isRequired: true,
        label: 'Country',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '4',
        triggersConditions: true,
        fieldOptions: ['ITALY', 'GEORGIA', 'USA'],
        // value: 'legal form value',
      },
      {
        displayOrder: 42,
        fieldName: 'city1',
        fieldType: 'TEXT',
        fieldWidth: '2',
        isRequired: true,
        label: 'City',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '5',
        conditionalFields: {
          country1: 'ITALY',
        },
        triggersConditions: false,
      },
      {
        displayOrder: 22,
        fieldName: 'radio2',
        fieldType: 'RADIO',
        fieldWidth: '2',
        isRequired: true,
        label: 'Choose One',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '123',
      },
      {
        displayOrder: 23,
        fieldName: 'multi4',
        fieldType: 'MULTI_CHECKBOX',
        fieldWidth: '2',
        isRequired: true,
        label: 'Select Multiple',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '456',
      },
      {
        displayOrder: 24,
        fieldName: 'multi5',
        fieldType: 'MULTI_CHECKBOX',
        fieldWidth: '2',
        isRequired: true,
        label: 'Select Multiple',
        pageOrder: 1,
        pageTitle: 'Company',
        rowGroup: '3',
        triggersConditions: false,
        fieldOptions: ['123', '456', '789'],
        // value: '789',
      },
    ],
    triggersConditions: false,
  },
  {
    displayOrder: 25,
    fieldName: 'vat',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'VAT Number',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    triggersConditions: false,
    validationRule: {
      regex: '^.{11}$',
    },
  },
  {
    displayOrder: 26,
    fieldName: 'name',
    fieldType: 'TEXT',
    fieldWidth: '3',
    isRequired: true,
    label: 'Company Name',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '4',
    triggersConditions: false,
    fieldOptions: [],
    validationRule: {
      regex: '^[a-zA-Zა-ჰ ]+$',
      minLength: 2,
      maxLength: 64,
    },
    // value: 'region value',
  },
  {
    displayOrder: 27,
    fieldName: 'legalFormType',
    fieldType: 'SELECT',
    fieldWidth: '3',
    isRequired: true,
    label: 'Company Type',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '4',
    triggersConditions: false,
    fieldOptions: ['PRIVATE_COMPANY', 'PUBLIC_COMPANY', 'NON_PROFIT'],
    // value: 'PRIVATE_COMPANY',
  },
  {
    displayOrder: 28,
    fieldName: 'country',
    fieldType: 'SELECT',
    fieldWidth: '3',
    isRequired: true,
    label: 'Country',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '4',
    triggersConditions: true,
    fieldOptions: ['ITALY', 'GEORGIA', 'USA'],
    // value: 'legal form value',
  },
  {
    displayOrder: 29,
    fieldName: 'sae',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'SAE Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '5',
    triggersConditions: false,
  },
  {
    displayOrder: 30,
    fieldName: 'city',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'City',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '5',
    conditionalFields: {
      country: 'ITALY',
      legalFormType: '!PUBLIC_COMPANY',
    },
    triggersConditions: false,
  },
  {
    displayOrder: 31,
    fieldName: 'ateco',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'ATECO Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '5',
    triggersConditions: false,
  },
  {
    displayOrder: 32,
    fieldName: 'rea',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'REA',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '6',
    triggersConditions: false,
    // value: 'rea value',
  },
  {
    displayOrder: 33,
    fieldName: 'cciaaReaNumber',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'REA Number',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '6',
    triggersConditions: false,
  },
  {
    displayOrder: 34,
    fieldName: 'cciaaReaProvince',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'Registration Province',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '7',
    triggersConditions: false,
    // value: 'provincia value',
  },
  {
    displayOrder: 35,
    fieldName: 'cciaaReaDate',
    fieldType: 'DATE',
    fieldWidth: '2',
    isRequired: true,
    label: 'Registration Date',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '7',
    triggersConditions: false,
    // value: '25/11/2015',
  },
  {
    displayOrder: 36,
    fieldName: 'taxCode5',
    fieldType: 'TEXT',
    fieldWidth: '2',
    isRequired: true,
    label: 'Tax Code',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '3',
    triggersConditions: false,
    validationRule: {
      regex: '^[A-Za-z0-9]+$',
      minLength: 16,
    },
    // value: '123142545345345435345',
  },
  {
    displayOrder: 37,
    fieldName: 'document',
    fieldType: 'FILE',
    fieldWidth: '2',
    isRequired: true,
    label: 'Document',
    pageOrder: 1,
    pageTitle: 'Company',
    rowGroup: '6',
    triggersConditions: false,
  },
];
